### ISSUE TITLE
Switch to using full-stack Compose file for production

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#144]
- [x] https://github.com/neurobagel/documentation/issues/187
- [x] https://github.com/neurobagel/planning/issues/147
- [x] https://github.com/neurobagel/recipes/issues/45

**Comment by surchs** [comment]
Things we want in the docs

- how to spin up `docker compose`
  - clone repo first, then make local changes
  - set .env variables
  - key .tsv for the important .env variables
- list of the profiles (replacing the different deployment sections)
  - incl when to use each
- keep around the "how to do this with curl" stuff in info boxes / box
- how to update versions
- the **important** .env variables
  - the unimportant ones could go somewhere else, e.g. a info box or separate "in depth page:
- how to clear the graph
- note: "do not download graphDB baremetal"

in depth
- change user permissions
- all the .env variables
- 

definitely remove:
- stardog stuff
-

**Comment by alyssadai** [comment]
Closing as all issues have been addressed.
