### ISSUE TITLE
Update namespace used for healthy controls/subject groups

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/planning#16]
- [ ] https://github.com/neurobagel/api/issues/180
- [ ] https://github.com/neurobagel/bagel-cli/issues/139
- [ ] https://github.com/neurobagel/documentation/issues/87
- [ ] update JSON and regenerate JSONLD files for https://github.com/neurobagel/openneuro-annotations

Maybe update:
- [ ] https://github.com/neurobagel/bulk_annotations/blob/435d529f62c3d2879f2cab8ae05e8ac0af04d0c7/heuristics.py#L81
- [ ] [bulk_annotation_levels annotation spreadsheet](https://docs.google.com/spreadsheets/d/1_6dnAjl2B2xse3uEB9UgKQziZeduZ9MDAVtUPW5IwIY/edit#gid=927345496) ?
