### ISSUE TITLE
OHBM 25 abstract

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#198]
We're going with the IDP discoverability

## TODO

- [x] Outline abstract
- [x] Discuss outline (anything to add feature wise before submission -> prefer no)
- [x] Decide on figures to create for abstract (if any)
- [x] Decide co-authors (input JB)
- [x] Early draft for co-author feedback (by Friday 6th of Dec)
- [x] Implement feedback by Friday 13th of Dec
- [x] Submit by Monday 16th of Dec

**Comment by surchs** [comment]
waiting for feedback
