### ISSUE TITLE
Annotation tool implementation

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#206]
## Context

New Annotation tool is being made. Here is the phases document: https://docs.google.com/document/d/18gjiJLavxYN5ExharaqepacINZnNVAXrIGN0GO5TGaY/edit?usp=sharing

## Why

- To make the annotation tool easier to maintain
- Turn it into a more generic tool that is potentially useful to several communities
- Design is done https://github.com/neurobagel/annotation-tool/issues/12
- Plan for the state is done https://github.com/neurobagel/annotation-tool/issues/17
- We're now going to build the tool

## Outcomes

- [ ] A fully functioning, nice and friendly annotation tool

## Releases / Functionality groups

We're going to build this tool in a number of functionality groups or releases until it provides the same functionality as the current annotation tool. Each release is going to be completed by one or several milestones that implement specific functionalities. 

### Release 1: BIDS data dictionary functionality, columns and 
Can create a BIDS data dictionary (columns and values) and load it again. No configuration ability yet, and no ability to link to Standardized variables and terms.

- [x] https://github.com/neurobagel/planning/issues/247
- [x] https://github.com/neurobagel/planning/issues/246

### Release 2: Ability to add semantic annotation for Standardized variables and Terms
Add ability to do semantic column annotation and also configurability.

- [ ] ...

### Release 3: Semantic annotation for values

- [ ] ...

### Release 4: Semantic annotation of multi-column values

- [ ]
