### ISSUE TITLE
Create a way of accessing SNOMED-CT assessments

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#209]
We want a source of all IDs and labels of clinical or cognitive assessments from SNOMED-CT so we can use them as our annotation and validation targets. 

Options are:

- manually created text files
- SNOMED term server: https://github.com/IHTSDO/snowstorm

## TODO
- [x] generate a .json file with the assessments
- [x] put the code either in dev-docs or a repo
- [x] document if we have any hierarchy in these terms

**Comment by surchs** [comment]
looking at code from https://github.com/neurobagel/planning/issues/52

**Comment by surchs** [comment]
Athena Concept ID of "Assessment scales (assessment scale)" is `4157120` from SNOMED

**Comment by surchs** [comment]
And the terms are unfortunately flat in SNOMED. Also not that many (~2500)
