### ISSUE TITLE
Add python version runners for 3.11 and 3.12

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#23]
For our python tools,  we should include 3.11 in the test runners - and probably also add 3.12 while we're at it (in the meantime also 13 and 14): https://devguide.python.org/versions/

We should also add to our tools a list of what python versions we support, e.g. https://shields.io/

We would want this (and don't have it yet) for ([checking python repos](https://github.com/orgs/neurobagel/repositories?q=language%3APython)):

- [ ] https://github.com/neurobagel/api/issues/546
- [ ] https://github.com/neurobagel/federation-api/issues/241
- [ ] https://github.com/neurobagel/tools/blob/main/.github/workflows/test.yml
- [ ] https://github.com/neurobagel/bump-dictionary/blob/main/.github/workflows/test.yaml (has 11 but not 12)
- [ ] https://github.com/neurobagel/digest/blob/main/.github/workflows/test.yml

Python repo but no test runners (yet) or test suite not using python:

- https://github.com/neurobagel/communities
- https://github.com/neurobagel/recipes
- https://github.com/neurobagel/vocab-handling/tree/main/src

We have it already for 

- [x] https://github.com/neurobagel/bagel-cli
- [x] https://github.com/neurobagel/configure-nb/blob/main/.github/workflows/test.yaml
