### ISSUE TITLE
Thursday coworking checklist

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#34]
To have a productive day together, let's do the following things beforehand:

goals are
- write down current (today's) capacities of our tools
- discuss the "gaps" 
- focus on annotation tool -> user persona -> what is most relevant / important

tasks are

- [x] start thinking of the "i am neurobagel" annotation oriented user persona
  - what does that user want to do
  - what capabilities are important to them
- [x] collect the annotation tool feedback @rmanaem 
  - [x] from appzi put it in a central place / shareable format
  - [x] from issues (if there are any)
- [x] for all our tools, prepare a short list of current capabilities that you think exist
  - [x] query @rmanaem 
  - [x] annotation @rmanaem 
  - [x] cli @alyssadai 
  - [x] dash @alyssadai 
  - [x] api @rmanaem 
  - [x] federation api @surchs 
  - [x] data model (can I have an "age" attached to a "session") @alyssadai 
  - [x] vocabulary (does CogAtlas have "EDS scores") @surchs 
  - [x] variables / CDEs (can I model "socioeconomic status" or "race") @surchs

**Comment by surchs** [comment]
here's our output: https://docs.google.com/document/d/1jzAWI6dzBCYVPsdczt3U49flOuWRPSOdDQmU9dBRelM/edit?usp=sharing

I'll close the issue with that, I think we achieved our goals for today 🎉
