### ISSUE TITLE
Grow userbase

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#49]
Dump of issues:

- [x] https://github.com/neurobagel/project/issues/110
- [x] https://github.com/neurobagel/documentation/issues/67
- [x] https://github.com/neurobagel/project/issues/47
- [ ] Have a walk-through style tutorial for setting up and adding data to a neurobagel node
