### ISSUE TITLE
Add logo to all tools

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#61]
- [x] https://github.com/neurobagel/annotation_tool/issues/633
- [x] https://github.com/neurobagel/query-tool/issues/275
- [x] https://github.com/neurobagel/documentation/issues/126
- [x] https://github.com/neurobagel/api/issues/221
- [x] https://github.com/neurobagel/federation-api/issues/18

Shows our neurobagel logo

**Comment by surchs** [comment]
@neurobagel/dev I think this thing should be 

- quick
- nice to have when we show the lab our update tomorrow

wdyt? split it up and prioritize it so we have it done by tomorrow?

**Comment by alyssadai** [comment]
Closing as all primary Neurobagel tools now have a logo! Dashboard logo will be updated separately as a part of rebrand https://github.com/neurobagel/proc_dash/issues/77
