### ISSUE TITLE
Add "in-progress" tag to all frontend tools

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#62]
- [x] https://github.com/neurobagel/digest/issues/114
- [x] https://github.com/neurobagel/annotation_tool/issues/645
- [x] https://github.com/neurobagel/query-tool/issues/293

Have a small UI element visible near the nav-bar that says "in-development" or simply "beta". Ideally this is accompanied by a text that explains what that means / what to expect (e.g. on-hover)

replaces https://github.com/neurobagel/project/issues/158

https://bootstrap-vue.org/docs/components/badge

**Comment by surchs** [comment]
Closing as completed
