### ISSUE TITLE
Refactor frontend query tool

### ISSUE THREAD

**Issue by surchs** [neurobagel/planning#96]
## Context
[Vue2 is end of life](https://v2.vuejs.org/lts/) since December, [Nuxt2 will be this summer](https://v2.nuxt.com/lts/). So issues like https://github.com/neurobagel/annotation_tool/issues/533 both become more frequent and harder to fix. Although LTS for Nuxt and Vue exists, the maintenance cost will likely become larger and migrating to a newer framework is most likely the right call and cheaper in the mid term. So we decided to move away from Nuxt2/Vue2. 

The obvious choice would be to go to Nuxt3. There are a couple of reasons why we won't do that:
- The Vue2-Vue3 transition has been slow for third party library support like component libraries. This is even more so the case for Nuxt3, which is not (yet?) supported e.g. by Cypress. So the ecosystem hasn't caught up yet, and existing solutions don't have a large userbase.
- Nuxt is a SSR framework. And while we get a bunch of quality of life features (file system routing, imports, fetch...), we ultimately don't need SSR for our tools. We pay for the convenience of Nuxt3 by being an even more niche framework than Vue3 - again making third party support worse
- We mainly picked Vue because we thought that it is the more accessible framework for contributors who may not be very familiar with JS. The first part is probably true, but out actual community is mostly using React. Certainly most freelancers do.

So bottom line: Nuxt (or any SSR) is overkill for our purposes. And for maintainability, third party ecosystem, documentation, availability of contributors React is superior to Vue. So we decided to migrate from Nuxt2 to React. We will do that with the query tool first.

https://miro.com/app/board/uXjVN9R29Aw=/?share_link_id=256256517932

## Why
- to update our tech stack for frontend services to a current framework
- to benefit from a wider tool and developer ecosystem
- to benefit from existing solutions for auth in the near future
- to ensure maintainability of the project frontend tools in the future

## Outcomes 
- [x] A new react based query tool repo exists
- [x] Build and dev tools are configured to current best practice and documented
- [ ] We have a tested query tool that has feature parity with the legacy Nuxt version

## What
- [x] neurobagel/react-query-tool#1
  - only one submit button
  - no query fields
  - tool renders the API response nicely
  - no UI sugar (toast, ellipses, blocking UI elements)
  - results cannot be selected
  - no download
  - no node selection
- [x] https://github.com/neurobagel/react-query-tool/issues/2
  - query fields for the variables exposed by the API are added
  - query selections are reflected in the API request being sent out
  - UI element blocking (healthy control <-> diagnosis)
  - fetch the options for variables from the API at startup
- [x] https://github.com/neurobagel/react-query-tool/issues/3
  - fetch the list of nodes from the API (with error handling)
  - default selection is all
  - User can select nodes and that becomes part of the request
- [x] https://github.com/neurobagel/react-query-tool/issues/4
  - selected nodes are read from URL query parameters on App launch
  - user node selections are written to the URL query parameters
  - base outcome: I can copy/paste URL with node names and recreate node selection state
- [x] https://github.com/neurobagel/react-query-tool/issues/5
  - select cards
  - download data
  - Alerts 
- [x] neurobagel/react-query-tool#14
  - Alerts
  - name ellipses
  - overall stats
 - [x] neurobagel/react-query-tool#18
 - [x] neurobagel/react-query-tool#20
 - [x] neurobagel/react-query-tool#28
 - [x] neurobagel/react-query-tool#27
 - [x] neurobagel/react-query-tool#41
 - [x] neurobagel/react-query-tool#42
